FROM node:18
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]
EXPOSE 3000
# RUN chown -R node /usr/src/app
# USER node
CMD ["tail", "-f", "/dev/null"]
