services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.web
  #   volumes:
  #     - .:/src
  #   dns: 8.8.8.8
  #   image: seisiun_web
  #   ports:
  #     - "8000:8000"
  #   links:
  #     - postgres
  #   environment:
  #     NODE_ENV: development
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  postgres:
    image: postgres:15.2-alpine
    container_name: seisiun_postgres
    network_mode: "bridge"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"