import type { FormKitNode } from '@formkit/core'

/**
  * @privateRemarks
  * This file was generated by the FormKit CLI and should not be manually
  * edited unless you’d like to "eject" from the CLI’s ability to update it.
  *
  * @checksum - 4644ad2561288be4149f56c4db286e8777dec380e62fd6115180bce352adeeee
  * @variables - radius=rounded-xl,accentColor=zinc,colorTemperature=zinc,spacing=2.5,scale=lg,inputShadow=shadow-md,baseColorShade=500,borderShadeLightMode=400,borderShadeDarkMode=400,inputMaxWidth=max-w-20em,tagRadius=rounded-full,swatchRadius=rounded-full
  * @theme - regenesis
  **/

 /**
  * This is the theme function itself, it should be imported and used as the
  * config.rootClasses function. For example:
  *
  * ```js
  * import { theme } from './formkit.theme'
  * import { defineFormKitConfig } from '@formkit/vue'
  *
  * export default defineFormKitConfig({
  *   config: {
  *     rootClasses: theme
  *   }
  * })
  * ```
  **/
 export function rootClasses (sectionName: string, node: FormKitNode): Record<string, boolean> {
   const key = `${node.props.type}__${sectionName}`
   const semanticKey = `formkit-${sectionName}`
   const familyKey = node.props.family ? `family:${node.props.family}__${sectionName}` : ''
   const memoKey = `${key}__${familyKey}`
   if (!(memoKey in classes)) {
     const sectionClasses = classes[key] ?? globals[sectionName] ?? {}
     sectionClasses[semanticKey] = true
     if (familyKey in classes) {
       classes[memoKey] = { ...classes[familyKey],  ...sectionClasses }
     } else {
       classes[memoKey] = sectionClasses
     }
   }
   return classes[memoKey] ?? { [semanticKey]: true }
 }

/**
 * These classes have already been merged with globals using tailwind-merge
 * and are ready to be used directly in the theme.
 **/
const classes: Record<string, Record<string, boolean>> = {
  'family:button__wrapper': {
    'group-data-[disabled="true"]:grayscale': true
  },
  'family:button__input': {
    'appearance-none': true,
    'rounded-3': true,
    'border': true,
    'border-zinc-400': true,
    'bg-zinc-600': true,
    'px-4': true,
    'py-2': true,
    // '[color-scheme:light]': true,
    // 'dark:[color-scheme:dark]': true,
    // 'selection:bg-zinc-100': true,
    // 'selection:text-zinc-700': true,
    // 'group-data-[has-overlay]:selection:!text-transparent': true,
    // 'font-bold': true,
    // 'rounded-xl': true,
    // 'outline-none': true,
    // 'flex': true,
    // '!text-base': true,
    // 'px-8': true,
    // 'py-3.5': true,
    // 'items-center': true,
    // 'mb-2': true,
    // 'text-base': true,
    // 'ring-offset-2': true,
    // 'focus-visible:ring-2': true,
    // 'group-data-[disabled]:!cursor-not-allowed': true,
    // 'shadow-md': true,
    // 'group-data-[prefix-icon]:pl-6': true,
    // 'group-data-[suffix-icon]:pr-6': true,
    // 'border': true,
    // 'border-zinc-500': true,
    // 'text-zinc-500': true,
    // 'group-[]/repeater:shadow': true,
    // 'group-[]/multistep:shadow': true,
    // 'dark:border-zinc-500': true
  },
  'family:box__wrapper': {
    'inline-flex': true,
    'items-center': true,
    'mb-1.5': true,
    'group-data-[multiple]:mb-0': true
  },
  'family:box__legend': {
    'block': true,
    'text-zinc-700': true,
    'text-base': true,
    'font-bold': true,
    'dark:text-zinc-300': true,
    'mb-2.5': true
  },
  'family:box__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'peer': true,
    'pointer-events-none': true,
    'absolute': true,
    'h-0': true,
    'w-0': true,
    'overflow-hidden': true,
    'opacity-0': true
  },
  'family:box__decorator': {
    'mr-2': true,
    'bg-white': true,
    'ring-zinc-400': true,
    // 'peer-checked:border-zinc-500': true,
    'relative': true,
    'block': true,
    'text-xl': true,
    'w-1em': true,
    'aspect-square': true,
    'border': true,
    'border-zinc-400': true,
    // 'text-transparent': true,
    // 'peer-checked:bg-zinc-50': true,
    // 'peer-checked:text-zinc-500': true,
    'peer-focus-visible:ring-2': true,
    'peer-focus-visible:ring-offset-1': true,
    'select-none': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'peer-disabled:bg-zinc-100': true,
    'group-data-[disabled]:grayscale': true,
    'shadow-md': true,
    'peer-disabled:cursor-not-allowed': true,
    // 'dark:border-zinc-400': true,
    // 'dark:bg-transparent': true,
    // 'dark:ring-offset-zinc-400': true,
    // 'dark:peer-focus-visible:ring-1': true,
    // 'dark:peer-disabled:bg-zinc-600/50': true,
    // 'dark:peer-checked:bg-zinc-800': true,
    // 'dark:peer-checked:text-zinc-300': true,
    // eslint-disable-next-line quotes
    "after:(content-[''] absolute left-1/2 top-1/2 flex max-h-[75%] max-w-[75%] -translate-x-1/2 -translate-y-1/2)": true,
    'peer-checked:after:i-uil-check': true,
  },
  'family:box__decoratorIcon': {
    'absolute': true,
    'left-1/2': true,
    'top-1/2': true,
    'flex': true,
    'h-full': true,
    'w-full': true,
    '-translate-x-1/2': true,
    '-translate-y-1/2': true,
  },
  'family:box__option': {
    'mb-1.5': true,
    'last:mb-0': true,
    'data-[disabled]:opacity-50': true,
    'data-[disabled]:select-none': true,
    'group-data-[disabled]:data-[disabled]:opacity-100': true
  },
  'family:box__label': {
    'block': true,
    'text-zinc-700': true,
    'text-lg': true,
    'fw-normal': true,
    'mb-1.5': true,
    '!mb-0': true,
    'dark:text-zinc-300': true
  },
  'family:box__optionHelp': {
    'text-zinc-500': true,
    'text-sm': true,
    '-mt-1': true,
    'mb-1.5': true,
    'ml-[min(2em,1.7rem)]': true,
    'relative': true,
    'left-0.5': true
  },
  'family:box__help': {
    'text-zinc-500': true,
    'text-sm': true,
    'dark:text-zinc-400': true,
    'mb-1.5': true,
    'group-data-[multiple]:mb-2.5': true,
    'group-data-[multiple]:-mt-1.5': true
  },
  'family:text__wrapper': {
    'flex': true,
    'flex-col': true,
    'items-start': true,
    'justify-start': true,
    'last:mb-0': true
  },
  'family:text__label': {
    'block': true,
    'text-zinc-700': true,
    'text-base': true,
    'font-bold': true,
    'dark:text-zinc-300': true,
    '!inline-flex': true,
    'mb-1.5': true
  },
  'family:text__inner': {
    'text-lg': true,
    'flex': true,
    'items-center': true,
    'w-full': true,
    'py-2.5': true,
    'px-3.5': true,
    // 'rounded-xl': true,
    // 'rounded-3': true,
    'rounded-[0.75em]': true,
    // 'rounded': true,
    'border': true,
    'border-zinc-400': true,
    'bg-white': true,
    'focus-within:ring-1': true,
    'focus-within:!ring-zinc-400': true,
    'focus-within:!border-zinc-400': true,
    'group-data-[invalid]:border-red-400': true,
    'group-data-[invalid]:ring-1': true,
    'group-data-[invalid]:ring-red-400': true,
    'group-data-[disabled]:bg-zinc-100': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'shadow-md': true,
    'dark:bg-transparent': true,
    'dark:border-zinc-400': true,
    'dark:group-data-[disabled]:bg-zinc-800/5': true,
    'dark:group-data-[invalid]:border-red-400': true,
    'dark:group-data-[invalid]:ring-red-400': true
  },
  'family:text__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'text-lg': true,
    'text-zinc-700': true,
    'min-w-0': true,
    'grow': true,
    'outline-none': true,
    'bg-transparent': true,
    'selection:bg-zinc-100': true,
    'placeholder:text-zinc-400': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'dark:placeholder-zinc-400/50': true,
    'dark:text-zinc-300': true,
    'border-none': true,
    'p-0': true,
    'focus:ring-0': true
  },
  'family:text__prefixIcon': {
    'flex': true,
    'items-center': true,
    '-ml-1': true,
    'mr-2.5': true,
    'text-lg': true,
    'h-1em': true,
    'w-1em': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    'text-zinc-600': true,
    'dark:text-zinc-300': true
  },
  'family:text__suffixIcon': {
    'flex': true,
    'items-center': true,
    '-mr-1.5': true,
    'ml-2.5': true,
    'text-lg': true,
    'h-1em': true,
    'w-1em': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    'text-zinc-600': true,
    'dark:text-zinc-300': true
  },
  'family:dropdown__wrapper': {
    'mb-2': true
  },
  'family:dropdown__inner': {
    'relative': true,
    'flex': true,
    'items-center': true,
    'bg-white': true,
    'border': true,
    'border-zinc-400': true,
    'rounded-xl': true,
    'group-data-[is-multiline]:!rounded-xl': true,
    'focus-within:ring-1': true,
    'focus-within:!ring-zinc-400': true,
    'focus-within:!border-zinc-400': true,
    'group-data-[invalid]:border-red-400': true,
    'group-data-[invalid]:ring-1': true,
    'group-data-[invalid]:ring-red-400': true,
    'group-data-[disabled]:bg-zinc-100': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'shadow-md': true,
    'group-[]/repeater:shadow-none': true,
    'group-[]/multistep:shadow-none': true,
    'dark:bg-transparent': true,
    'dark:border-zinc-400': true,
    'dark:group-data-[disabled]:bg-zinc-700/40': true,
    'dark:group-data-[invalid]:border-red-400': true,
    'dark:group-data-[invalid]:ring-red-400': true
  },
  'family:dropdown__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'grow': true,
    'p-2.5': true,
    'pr-0': true,
    'pl-3.5': true,
    'text-lg': true,
    'text-zinc-700': true,
    'text-ellipsis': true,
    'min-w-0': true,
    'outline-none': true,
    'bg-transparent': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'group-data-[prefix-icon]:!pl-0': true,
    'group-data-[suffix-icon]:!pr-0': true,
    'placeholder:text-zinc-400': true,
    'selection:bg-zinc-100': true,
    'dark:placeholder:text-zinc-500': true,
    'dark:text-zinc-300': true,
    'border-none': true,
    'focus:ring-0': true,
    'bg-none': true
  },
  'family:dropdown__listboxButton': {
    'w-[2.5em]': true,
    'self-stretch': true,
    'text-lg': true,
    'flex': true,
    'items-center': true,
    'text-zinc-700': true,
    'z-10': true,
    'dark:text-zinc-300': true,
    'data-[disabled]:cursor-not-allowed': true
  },
  'family:dropdown__removeSelection': {
    'w-[2.5em]': true,
    'self-stretch': true,
    'text-lg': true,
    'flex': true,
    'items-center': true,
    'text-zinc-700': true,
    'hover:text-red-400': true,
    'z-10': true,
    'dark:text-zinc-300': true
  },
  'family:dropdown__selectIcon': {
    'text-lg': true,
    'inline-flex': true,
    'justify-center': true,
    'w-[2.5em]': true,
    'relative': true,
    'my-auto': true,
    '[&>svg]:w-[1em]': true,
    '[&>svg]:mx-auto': true
  },
  'family:dropdown__closeIcon': {
    'text-lg': true,
    'w-[0.75em]': true,
    'relative': true,
    'm-auto': true
  },
  'family:dropdown__prefixIcon': {
    'flex': true,
    'items-center': true,
    '-ml-1': true,
    'mr-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    '!ml-2.5': true,
    '!mr-0': true,
    'text-zinc-600': true,
    'dark:text-zinc-300': true
  },
  'family:dropdown__suffixIcon': {
    'flex': true,
    'items-center': true,
    '-mr-1.5': true,
    'ml-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    '!mr-2.5': true,
    '!ml-0': true,
    'text-zinc-600': true,
    'dark:text-zinc-300': true
  },
  'family:dropdown__dropdownWrapper': {
    'rounded-xl': true,
    'shadow-xl': true,
    'mt-1.5': true,
    'group-data-[expanded]:opacity-100': true,
    'group-data-[overscroll]:m-0': true,
    'group-data-[overscroll]:shadow-none': true
  },
  'family:dropdown__listbox': {
    'bg-white': true,
    'rounded-xl': true,
    'shadow-xl': true,
    'overflow-clip': true,
    'empty:hidden': true,
    'border': true,
    'border-zinc-300': true,
    'dark:bg-zinc-800': true,
    'dark:border-zinc-500': true
  },
  'family:dropdown__listitem': {
    'relative': true,
    'flex': true,
    'items-center': true,
    'px-2.5': true,
    'py-2': true,
    'first:pt-2.5': true,
    'last:pb-2.5': true,
    'text-zinc-700': true,
    'text-lg': true,
    'data-[is-active]:bg-zinc-100': true,
    'dark:text-zinc-200': true,
    'dark:data-[is-active]:text-zinc-700': true,
    'before:content-[\'\']': true,
    'before:absolute': true,
    'before:inset-0': true,
    'data-[is-active]:first:before:rounded-xl': true,
    'data-[is-active]:first:before:rounded-b-none': true,
    'data-[is-active]:last:before:rounded-xl': true,
    'data-[is-active]:last:before:rounded-t-none': true,
    'data-[is-active]:first:last:before:rounded-xl': true,
    'data-[is-active]:before:ring-1': true,
    'data-[is-active]:before:ring-zinc-400': true,
    'data-[is-active]:before:ring-inset': true,
    'data-[is-active]:before:ring-offset-zinc-100': true
  },
  'family:dropdown__selectedIcon': {
    'flex': true,
    'absolute': true,
    'items-center': true,
    'text-zinc-500': true,
    'left-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true
  },
  'family:dropdown__option': {
    'ml-[1.5em]': true
  },
  'family:dropdown__loadMoreInner': {
    'flex': true,
    'text-base': true,
    'text-zinc-500': true,
    'p-2.5': true,
    'items-center': true,
    'justify-center': true,
    '[&>span]:mr-2.5': true,
    'hover:text-zinc-500': true,
    'cursor-pointer': true,
    'dark:text-zinc-200': true,
    'dark:hover:text-zinc-400': true
  },
  'family:dropdown__selectionWrapper': {
    'grow': true,
    'flex': true,
    'items-center': true,
    'text-zinc-700': true
  },
  'family:dropdown__selection': {
    'grow': true,
    'text-zinc-700': true,
    'group-data-[multiple]:p-2.5': true,
    'dark:text-zinc-300': true
  },
  'family:dropdown__tagsWrapper': {
    'w-full': true
  },
  'family:dropdown__tagWrapper': {
    'group/tag': true,
    'rounded-full': true,
    'mr-1.5': true,
    'mb-1.5': true,
    'outline-none': true,
    'data-[active-selection=true]:ring-2': true,
    'data-[active-selection=true]:ring-zinc-400': true
  },
  'family:dropdown__tags': {
    'inline-flex': true,
    'flex-wrap': true,
    'items-center': true,
    'w-full': true,
    '-mb-1.5': true,
    'empty:mb-0': true
  },
  'family:dropdown__tag': {
    'flex': true,
    'items-center': true,
    'cursor-default': true,
    'rounded-full': true,
    'text-sm': true,
    'px-2': true,
    'py-1': true,
    'bg-zinc-500': true,
    'text-white': true,
    '[&>[type=button]]:!w-[0.5em]': true,
    '[&>[type=button]]:aspect-square': true,
    '[&>[type=button]]:!text-inherit': true,
    '[&>[type=button]]:cursor-pointer': true,
    'group-data-[active-selection=true]/tag:bg-zinc-300': true,
    'group-data-[active-selection=true]/tag:text-zinc-700': true
  },
  'family:dropdown__tagLabel': {
    'mr-1': true
  },
  'family:dropdown__emptyMessage': {
    'flex': true,
    'items-center': true,
    'px-2.5': true,
    'py-2': true,
    'first:pt-2.5': true,
    'last:pb-2.5': true,
    'text-zinc-700': true,
    'text-base': true,
    'aria-selected:text-white': true,
    'aria-selected:bg-zinc-500': true
  },
  'button__input': {
    // 'appearance-none': true,
    // '[color-scheme:light]': true,
    // 'dark:[color-scheme:dark]': true,
    // 'selection:bg-zinc-100': true,
    // 'selection:text-zinc-700': true,
    // 'group-data-[has-overlay]:selection:!text-transparent': true,
    // 'rounded': true
    // 'bg-zinc-50': true,
    // 'hover:bg-zinc-100': true,
    // 'dark:text-zinc-500': true,
    // 'dark:bg-transparent': true,
    // 'dark:hover:bg-zinc-50/5': true
  },
  'checkbox__decorator': {
    'rounded': true
  },
  'checkbox__decoratorIcon': {
    'max-w-[66.66%]': true
  },
  'color__inner': {
    '!w-auto': true,
    '!p-1.5': true,
    '!inline-flex': true,
    'group-data-[prefix-icon]:border': true,
    'group-data-[prefix-icon]:border-zinc-400': true,
    'group-data-[suffix-icon]:border': true,
    'group-data-[suffix-icon]:border-zinc-400': true,
    'dark:group-data-[prefix-icon]:border-zinc-400': true,
    'dark:group-data-[suffix-icon]:border-zinc-400': true
  },
  'color__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    '!w-14': true,
    'bg-transparent': true,
    'cursor-pointer': true,
    'rounded-xl': true,
    'overflow-clip': true,
    '[&::-webkit-color-swatch-wrapper]:p-0': true,
    '[&::-webkit-color-swatch]:border-none': true,
    '[&::-moz-color-swatch]:border-none': true,
    'group-data-[prefix-icon]:mx-2.5': true,
    'group-data-[suffix-icon]:mx-2.5': true
  },
  'color__prefixIcon': {
    'flex': true,
    'items-center': true,
    '-ml-1': true,
    'mr-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    'group-data-[prefix-icon]:m-1.5': true,
    'group-data-[prefix-icon]:mr-0': true
  },
  'color__suffixIcon': {
    'flex': true,
    'items-center': true,
    '-mr-1.5': true,
    'ml-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    'group-data-[suffix-icon]:m-1.5': true,
    'group-data-[prefix-icon]:ml-0': true
  },
  'date__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'focus:[&::-webkit-datetime-edit-day-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-month-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-year-field]:bg-zinc-100': true
  },
  'datetime-local__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'focus:[&::-webkit-datetime-edit-day-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-month-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-year-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-hour-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-minute-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-ampm-field]:bg-zinc-100': true
  },
  'file__fileList': {
    'group/list': true,
    'peer': true,
    'w-full': true,
    'min-w-0': true,
    'data-[has-multiple]:mb-[1.25em]': true
  },
  'file__fileItemIcon': {
    'h-[1em]': true,
    'w-[1em]': true,
    'mr-2.5': true,
    'shrink-0': true
  },
  'file__fileItem': {
    'flex': true,
    'min-w-0': true,
    'items-center': true,
    'text-zinc-700': true,
    'mb-2': true,
    'last:mb-0': true,
    'dark:text-zinc-300': true
  },
  'file__fileName': {
    'truncate': true,
    'min-w-0': true,
    'w-full': true,
    'shrink': true,
    'leading-5': true,
    'group-data-[has-multiple]/list:text-base': true
  },
  'file__fileRemove': {
    'right-2.5': true,
    'ring-zinc-400': true,
    'rounded-xl': true,
    'z-20': true,
    'flex': true,
    'appearance-none': true,
    'items-center': true,
    'text-[0px]': true,
    'outline-none': true,
    'hover:!text-red-400': true,
    'focus-visible:ring-2': true,
    'group-data-[disabled]:pointer-events-none': true,
    'group-data-[disabled]:!text-zinc-500': true,
    'peer-data-[has-multiple]:absolute': true,
    'peer-data-[has-multiple]:bottom-[max(0.5em,8px)]': true,
    'peer-data-[has-multiple]:left-3.5': true,
    'peer-data-[has-multiple]:text-zinc-500': true,
    'peer-data-[has-multiple]:text-sm': true,
    'peer-data-[has-multiple]:whitespace-nowrap': true,
    'group-data-[prefix-icon]:peer-data-[has-multiple]:left-2.5': true,
    'dark:hover:!text-red-400': true
  },
  'file__fileRemoveIcon': {
    'block': true,
    'text-base': true,
    'w-[0.75em]': true,
    'relative': true,
    'z-10': true
  },
  'file__inner': {
    'relative': true,
    'cursor-pointer': true,
    'group-data-[has-multiple]:rounded-xl': true
  },
  'file__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'cursor-pointer': true,
    'text-transparent': true,
    'absolute': true,
    'inset-0': true,
    'opacity-0': true,
    'z-10': true,
    'file:pointer-events-none': true,
    'file:w-0': true,
    'file:h-0': true,
    'file:overflow-hidden': true
  },
  'file__noFiles': {
    'flex': true,
    'w-full': true,
    'items-center': true,
    'text-zinc-400': true,
    'dark:text-zinc-500': true
  },
  'file__noFilesIcon': {
    'w-[1em]': true,
    'mr-2.5': true
  },
  'form__form': {
    '': true
  },
  'form__actions': {
    '': true
  },
  'form__summaryInner': {
    'group/summary': true,
    'border': true,
    'border-zinc-400': true,
    'bg-white': true,
    'rounded-xl': true,
    'py-2.5': true,
    'px-3.5': true,
    'shadow-md': true,
    'dark:bg-transparent': true,
    'dark:border-zinc-400': true
  },
  'form__summaryHeader': {
    'text-xl': true,
    'text-zinc-700': true,
    'font-bold': true,
    'mb-2.5': true,
    'dark:text-zinc-300': true
  },
  'form__messages': {
    '': true
  },
  'form__message': {
    'text-red-500': true,
    'mb-2': true,
    'text-sm': true,
    'dark:text-red-400': true,
    'group-[]/summary:text-base': true
  },
  'form__messageLink': {
    'group-[]/summary:outline-none': true,
    'group-[]/summary:focus-visible:ring-2': true,
    'group-[]/summary:ring-zinc-500': true
  },
  'month__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'focus:[&::-webkit-datetime-edit-month-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-year-field]:bg-zinc-100': true
  },
  'radio__decorator': {
    // 'rounded-full': true
    'rounded-1/2': true,
  },
  // 'radio__decoratorIcon': {
  //   'max-w-[50%]': true
  // },
  'range__inner': {
    'relative': true,
    '!border-none': true,
    '!ring-0': true,
    '!px-0': true,
    '!bg-transparent': true,
    '!shadow-none': true
  },
  'range__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'group/input': true,
    'cursor-pointer': true,
    '[&::-webkit-slider-runnable-track]:bg-zinc-400/50': true,
    '[&::-webkit-slider-runnable-track]:h-[0.25em]': true,
    '[&::-webkit-slider-runnable-track]:rounded-xl': true,
    'dark:[&::-webkit-slider-runnable-track]:bg-zinc-400/50': true,
    '[&::-webkit-slider-thumb]:appearance-none': true,
    '[&::-webkit-slider-thumb]:w-[0.85em]': true,
    '[&::-webkit-slider-thumb]:aspect-square': true,
    '[&::-webkit-slider-thumb]:bg-zinc-500': true,
    '[&::-webkit-slider-thumb]:rounded-full': true,
    '[&::-webkit-slider-thumb]:relative': true,
    '[&::-webkit-slider-thumb]:top-1/2': true,
    '[&::-webkit-slider-thumb]:-translate-y-1/2': true,
    '[&::-webkit-slider-thumb]:group-data-[disabled]:bg-zinc-500': true,
    '[&::-webkit-slider-thumb]:group-data-[disabled]:!ring-zinc-300': true,
    '[&::-webkit-slider-thumb]:focus-visible:ring-2': true,
    '[&::-webkit-slider-thumb]:focus:!ring-zinc-400': true,
    '[&::-webkit-slider-thumb]:focus:ring-offset-2': true,
    '[&::-webkit-slider-thumb]:shadow-md': true,
    'dark:[&::-webkit-slider-thumb]:group-data-[disabled]:!ring-zinc-500': true,
    'dark:[&::-webkit-slider-thumb]:focus:ring-offset-zinc-700': true,
    '[&::-moz-range-track]:bg-zinc-400/50': true,
    '[&::-moz-range-track]:h-[0.25]': true,
    '[&::-moz-range-track]:rounded-xl': true,
    'dark:[&::-moz-range-track]:bg-zinc-400/50': true,
    '[&::-moz-range-thumb]:appearance-none': true,
    '[&::-moz-range-thumb]:border-none': true,
    '[&::-moz-range-thumb]:w-[0.85em]': true,
    '[&::-moz-range-thumb]:h-[0.85em]': true,
    '[&::-moz-range-thumb]:bg-zinc-500': true,
    '[&::-moz-range-thumb]:rounded-full': true,
    '[&::-moz-range-thumb]:group-data-[disabled]:bg-zinc-500': true,
    '[&::-moz-range-thumb]:group-data-[disabled]:!ring-zinc-300': true,
    '[&::-moz-range-thumb]:focus-visible:ring-2': true,
    '[&::-moz-range-thumb]:focus:!ring-zinc-400': true,
    '[&::-moz-range-thumb]:focus:ring-offset-2': true,
    '[&::-moz-range-thumb]:shadow-md': true,
    'dark:[&::-moz-range-thumb]:group-data-[disabled]:!ring-zinc-500': true,
    'dark:[&::-moz-range-thumb]:focus:ring-offset-zinc-700': true
  },
  'select__wrapper': {
    'mb-2': true
  },
  'select__inner': {
    'relative': true,
    'flex': true,
    'items-center': true,
    'bg-white': true,
    'border': true,
    'border-zinc-400': true,
    'rounded-xl': true,
    'focus-within:ring-1': true,
    'focus-within:!ring-zinc-400': true,
    'focus-within:!border-zinc-400': true,
    'group-data-[invalid]:border-red-400': true,
    'group-data-[invalid]:ring-1': true,
    'group-data-[invalid]:ring-red-400': true,
    'group-data-[disabled]:bg-zinc-100': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'shadow-md': true,
    'group-[]/repeater:shadow-none': true,
    'group-[]/multistep:shadow-none': true,
    'group-data-[multiple]:rounded-xl': true,
    'dark:bg-transparent': true,
    'dark:border-zinc-400': true,
    'dark:group-data-[disabled]:bg-zinc-800/5': true,
    'dark:group-data-[invalid]:border-red-400': true,
    'dark:group-data-[invalid]:ring-red-400': true
  },
  'select__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'grow': true,
    'p-2.5': true,
    'py-2.5': true,
    'px-3.5': true,
    'pr-[2em]': true,
    'text-lg': true,
    'text-zinc-700': true,
    'text-ellipsis': true,
    'min-w-0': true,
    'outline-none': true,
    'bg-transparent': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'group-data-[prefix-icon]:!pl-0': true,
    'group-data-[suffix-icon]:!pr-0': true,
    'data-[placeholder]:text-zinc-400': true,
    'group-data-[multiple]:!p-0': true,
    'selection:bg-zinc-100': true,
    'dark:data-[placeholder]:text-zinc-400/50': true,
    'dark:text-zinc-300': true,
    'border-none': true,
    'focus:ring-0': true,
    'bg-none': true
  },
  'select__selectIcon': {
    'absolute': true,
    'w-[1em]': true,
    'text-zinc-700': true,
    'pointer-events-none': true,
    'right-2.5': true,
    'group-data-[suffix-icon]:mr-[1.5em]': true,
    'dark:text-zinc-300': true
  },
  'select__optGroup': {
    'group/optgroup': true,
    'group-data-[multiple]:px-1.5': true,
    'pt-1.5': true,
    'font-bold': true,
    'text-base': true
  },
  'select__option': {
    'group-data-[disabled]:opacity-50': true,
    'group-data-[disabled]:select-none': true,
    'group-data-[multiple]:checked:bg-zinc-100': true,
    'group-data-[multiple]:focus:bg-zinc-100': true,
    'group-data-[multiple]:text-base': true,
    'group-data-[multiple]:outline-none': true,
    'group-data-[multiple]:border-none': true,
    'group-data-[multiple]:py-2': true,
    'group-data-[multiple]:px-2.5': true,
    'dark:group-data-[multiple]:focus:bg-zinc-700': true,
    'dark:group-data-[multiple]:checked:bg-zinc-700': true
  },
  'select__prefixIcon': {
    'flex': true,
    'items-center': true,
    'mr-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    'ml-2.5': true,
    'text-zinc-600': true,
    'dark:text-zinc-300': true
  },
  'select__suffixIcon': {
    'flex': true,
    'items-center': true,
    'ml-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    'mr-2.5': true,
    'text-zinc-600': true,
    'dark:text-zinc-300': true
  },
  'submit__outer': {
    'group': true,
    'max-w-20em': true,
    'min-w-0': true,
    'grow': true,
    'mb-4': true,
    'data-[disabled]:select-none': true,
    'text-lg': true,
    'data-[disabled]:opacity-100': true
  },
  'submit__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'bg-zinc-500': true,
    '!text-white': true,
    'active:text-zinc-100': true,
    'active:bg-zinc-600': true,
    'hover:bg-zinc-600': true,
    'disabled:border-zinc-400': true,
    'disabled:bg-zinc-400': true,
    'disabled:text-zinc-100': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'dark:disabled:border-zinc-100': true,
    'dark:disabled:bg-zinc-500': true,
    'dark:disabled:text-zinc-200': true,
    'dark:text-white': true,
    'dark:ring-offset-zinc-400': true,
    'group-data-[loading=true]/form:before:content[\'\']': true,
    'group-data-[loading=true]/form:before:block': true,
    'group-data-[loading=true]/form:before:animate-spin': true,
    'group-data-[loading=true]/form:before:w-5': true,
    'group-data-[loading=true]/form:before:h-5': true,
    'group-data-[loading=true]/form:before:rounded-full': true,
    'group-data-[loading=true]/form:before:mr-3.5': true,
    'group-data-[loading=true]/form:before:-ml-2': true,
    'group-data-[loading=true]/form:before:border-2': true,
    'group-data-[loading=true]/form:before:border-solid': true,
    'group-data-[loading=true]/form:before:border-white': true,
    'group-data-[loading=true]/form:before:border-r-transparent': true
  },
  'submit__prefixIcon': {
    'flex': true,
    'items-center': true,
    '-ml-1': true,
    'mr-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    'text-zinc-100': true
  },
  'submit__suffixIcon': {
    'flex': true,
    'items-center': true,
    '-mr-1.5': true,
    'ml-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    'text-zinc-100': true
  },
  'textarea__inner': {
    'flex': true,
    'items-center': true,
    'mb-2': true,
    'bg-white': true,
    'border': true,
    'border-zinc-400': true,
    'rounded-xl': true,
    'focus-within:ring-1': true,
    'focus-within:!ring-zinc-400': true,
    'focus-within:!border-zinc-400': true,
    'group-data-[invalid]:border-red-400': true,
    'group-data-[invalid]:ring-1': true,
    'group-data-[invalid]:ring-red-400': true,
    'group-data-[disabled]:bg-zinc-100': true,
    'shadow-md': true,
    'group-[]/repeater:shadow-none': true,
    'group-[]/multistep:shadow-none': true,
    'dark:border-zinc-400': true,
    'dark:group-data-[disabled]:bg-zinc-800/5': true,
    'dark:group-data-[invalid]:border-red-400': true,
    'dark:group-data-[invalid]:ring-red-400': true,
    'dark:bg-transparent': true
  },
  'textarea__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'text-lg': true,
    'h-28': true,
    'text-zinc-700': true,
    'min-w-0': true,
    'grow': true,
    'shrink': true,
    '!py-2.5': true,
    '!px-3.5': true,
    'outline-none': true,
    'bg-transparent': true,
    'selection:bg-zinc-100': true,
    'placeholder:text-zinc-400': true,
    'group-data-[disabled]:!cursor-not-allowed': true,
    'dark:placeholder-zinc-400/50': true,
    'dark:text-zinc-300': true,
    'p-0': true,
    'border-none': true,
    'focus:ring-0': true
  },
  'textarea__prefixIcon': {
    'flex': true,
    'items-center': true,
    '-ml-1': true,
    'mr-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    '!ml-2.5': true,
    '!mr-0': true,
    'text-zinc-600': true,
    'dark:text-zinc-300': true
  },
  'textarea__suffixIcon': {
    'flex': true,
    'items-center': true,
    '-mr-1.5': true,
    'ml-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true,
    '!mr-2.5': true,
    '!ml-0': true,
    'text-zinc-600': true,
    'dark:text-zinc-300': true
  },
  'time__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'focus:[&::-webkit-datetime-edit-hour-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-minute-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-ampm-field]:bg-zinc-100': true
  },
  'week__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'focus:[&::-webkit-datetime-edit-week-field]:bg-zinc-100': true,
    'focus:[&::-webkit-datetime-edit-year-field]:bg-zinc-100': true
  },
  'autocomplete__selections': {
    'flex': true,
    'absolute': true,
    'inset-0': true,
    'group-data-[multiple]:static': true,
    'group-data-[multiple]:block': true,
    'group-data-[empty]:hidden': true,
    'group-data-[multiple]:mt-2': true
  },
  'autocomplete__selectionWrapper': {
    'bg-zinc-100': true,
    'rounded-xl': true,
    'group-data-[multiple]:border': true,
    'group-data-[multiple]:border-zinc-300': true,
    'group-data-[multiple]:mb-2': true,
    'outline-none': true,
    'data-[active-selection=true]:ring-2': true,
    'data-[active-selection=true]:ring-zinc-400': true,
    'dark:bg-zinc-600': true,
    'dark:group-data-[multiple]:border-zinc-400': true,
    '[&.formkit-dropZone]:opacity-25': true,
    '[&.formkit-touchDropZone]:opacity-25': true,
    '[&.formkit-touchDragging]:!flex': true,
    '[&.formkit-longTouch]:opacity-25': true
  },
  'autocomplete__selection': {
    'rounded-xl': true,
    'just': true,
    'pl-2.5': true,
    '[&>*]:ml-0': true,
    'dark:text-zinc-200': true
  },
  'rating__inner': {
    'flex': true,
    'w-[130px]': true,
    'items-center': true,
    'relative': true
  },
  'rating__itemsWrapper': {
    'w-full': true
  },
  'rating__onItems': {
    'text-yellow-400': true
  },
  'rating__offItems': {
    'text-zinc-400': true
  },
  'rating__onItemWrapper': {
    '[&>*]:w-full': true,
    '[&>*]:h-auto': true,
    '[&>*]:max-w-none': true,
    '[&>*]:max-h-none': true
  },
  'rating__offItemWrapper': {
    '[&>*]:w-full': true,
    '[&>*]:h-auto': true,
    '[&>*]:max-w-none': true,
    '[&>*]:max-h-none': true
  },
  'rating__ratingIcon': {
    'w-full': true
  },
  'toggle__outer': {
    'group': true,
    'min-w-0': true,
    'grow': true,
    'mb-4': true,
    'data-[disabled]:select-none': true,
    'data-[disabled]:opacity-50': true,
    'text-lg': true,
    'max-w-none': true
  },
  'toggle__altLabel': {
    'block': true,
    'w-full': true,
    'mb-2': true,
    'font-bold': true,
    'text-sm': true,
    'text-zinc-700': true,
    'dark:text-zinc-300': true
  },
  'toggle__inner': {
    'peer': true,
    'inline-block': true,
    'mr-2.5': true
  },
  'toggle__input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true,
    'peer': true,
    'absolute': true,
    'opacity-0': true,
    'w-0': true,
    'h-0': true
  },
  'toggle__label': {
    'block': true,
    'text-zinc-700': true,
    'text-base': true,
    'font-bold': true,
    'mb-1.5': true,
    'dark:text-zinc-300': true,
    'peer-first:font-normal': true,
    'peer-first:mb-0': true
  },
  'toggle__innerLabel': {
    'absolute': true,
    'text-zinc-200': true,
    'text-[10px]': true,
    'font-bold': true,
    'select-none': true,
    'left-full': true,
    'top-1/2': true,
    '-translate-x-full': true,
    '-translate-y-1/2': true,
    'px-1': true
  },
  'toggle__thumb': {
    'relative': true,
    'p-0.5': true,
    'left-0': true,
    'aspect-square': true,
    'rounded-full': true,
    'transition-all': true,
    'w-[1.25em]': true,
    'bg-zinc-50': true,
    'text-zinc-600': true,
    'shadow-base': true
  },
  'toggle__track': {
    'p-0.5': true,
    'min-w-[3em]': true,
    'relative': true,
    'cursor-pointer': true,
    'select-none': true,
    'rounded-full': true,
    'transition-all': true,
    'bg-zinc-400': true,
    'peer-checked:bg-zinc-500': true,
    'peer-checked:[&>div:last-child]:left-full': true,
    'peer-checked:[&>div:last-child]:-translate-x-full': true,
    'peer-checked:[&>div:first-child:not(:last-child)]:left-0': true,
    'peer-checked:[&>div:first-child:not(:last-child)]:translate-x-0': true,
    'shadow': true,
    'peer-focus-visible:ring-2': true,
    'peer-focus-visible:ring-zinc-400': true,
    'peer-focus-visible:ring-offset-2': true,
    'dark:bg-zinc-500': true
  },
  'toggle__valueLabel': {
    'font-bold': true,
    'text-sm': true,
    'text-zinc-700': true,
    'dark:text-zinc-300': true
  },
  // 'toggle__wrapper': {
  //   'flex': true,
  //   'flex-wrap': true,
  //   'items-center': true,
  //   'mb-1.5': true
  // },
  // 'togglebuttons__wrapper': {
  //   'mb-2': true
  // },
  // 'togglebuttons__options': {
  //   'group/options': true,
  //   'inline-flex': true,
  //   'data-[vertical="true"]:flex-col': true
  // },
  // 'togglebuttons__option': {
  //   'group/option': true
  // },
  // 'togglebuttons__input': {
  //   'appearance-none': true,
  //   '[color-scheme:light]': true,
  //   'dark:[color-scheme:dark]': true,
  //   'selection:bg-zinc-100': true,
  //   'selection:text-zinc-700': true,
  //   'group-data-[has-overlay]:selection:!text-transparent': true,
  //   '!px-5': true,
  //   '!mb-0': true,
  //   'relative': true,
  //   'focus:z-10': true,
  //   'group-data-[vertical="true"]/options:w-full': true,
  //   'justify-center': true,
  //   'bg-zinc-50': true,
  //   'disabled:opacity-50': true,
  //   'disabled:cursor-not-allowed': true,
  //   'group-data-[disabled]:disabled:opacity-100': true,
  //   'dark:bg-transparent': true,
  //   'dark:disabled:bg-transparent': true,
  //   'dark:disabled:text-zinc-500': true,
  //   'dark:text-zinc-500': true,
  //   'aria-[pressed="true"]:bg-zinc-500': true,
  //   'aria-[pressed="true"]:text-white': true,
  //   'dark:aria-[pressed="true"]:bg-zinc-500': true,
  //   'dark:aria-[pressed="true"]:text-white': true,
  //   'group-[]/option:!rounded-none': true,
  //   'group-data-[vertical="false"]/options:group-first/option:!rounded-xl': true,
  //   'group-data-[vertical="true"]/options:group-first/option:!rounded-xl': true,
  //   'group-data-[vertical="false"]/options:group-first/option:!rounded-tr-none': true,
  //   'group-data-[vertical="false"]/options:group-first/option:!rounded-br-none': true,
  //   'group-data-[vertical="true"]/options:group-first/option:!rounded-bl-none': true,
  //   'group-data-[vertical="true"]/options:group-first/option:!rounded-br-none': true,
  //   'group-data-[vertical="false"]/options:group-last/option:!rounded-xl': true,
  //   'group-data-[vertical="true"]/options:group-last/option:!rounded-xl': true,
  //   'group-data-[vertical="false"]/options:group-last/option:!rounded-tl-none': true,
  //   'group-data-[vertical="false"]/options:group-last/option:!rounded-bl-none': true,
  //   'group-data-[vertical="true"]/options:group-last/option:!rounded-tl-none': true,
  //   'group-data-[vertical="true"]/options:group-last/option:!rounded-tr-none': true,
  //   'group-data-[vertical="false"]/options:group-[]/option:!border-r-0': true,
  //   'group-data-[vertical="false"]/options:group-last/option:!border-r': true,
  //   'group-data-[vertical="false"]/options:group-[]/option:aria-[pressed="true"]:border-x-zinc-500': true,
  //   'group-data-[vertical="false"]/options:group-first/option:aria-[pressed="true"]:border-l-zinc-500': true,
  //   'group-data-[vertical="false"]/options:group-last/option:aria-[pressed="true"]:border-r-zinc-500': true,
  //   'dark:group-data-[vertical="false"]/options:group-[]/option:aria-[pressed="true"]:border-x-zinc-500': true,
  //   'dark:group-data-[vertical="false"]/options:group-first/option:aria-[pressed="true"]:border-l-zinc-500': true,
  //   'dark:group-data-[vertical="false"]/options:group-last/option:aria-[pressed="true"]:border-r-zinc-500': true,
  //   'group-data-[vertical="true"]/options:group-[]/option:!border-b-0': true,
  //   'group-data-[vertical="true"]/options:group-last/option:!border-b': true,
  //   'group-data-[vertical="true"]/options:group-[]/option:aria-[pressed="true"]:border-y-zinc-500': true,
  //   'group-data-[vertical="true"]/options:group-first/option:aria-[pressed="true"]:border-t-zinc-500': true,
  //   'group-data-[vertical="true"]/options:group-last/option:aria-[pressed="true"]:border-b-zinc-500': true,
  //   'dark:group-data-[vertical="true"]/options:group-[]/option:aria-[pressed="true"]:border-y-zinc-500': true,
  //   'dark:group-data-[vertical="true"]/options:group-first/option:aria-[pressed="true"]:border-t-zinc-500': true,
  //   'dark:group-data-[vertical="true"]/options:group-last/option:aria-[pressed="true"]:border-b-zinc-500': true
  // },
}

/**
 * Globals are merged prior to generating this file — these are included for
 * any other non-matching inputs.
 **/
const globals: Record<string, Record<string, boolean>> = {
  'outer': {
    'group': true,
    'max-w-20em': true,
    'min-w-0': true,
    'grow': true,
    'data-[disabled]:select-none': true,
    'data-[disabled]:opacity-50': true,
    'text-lg': true
  },
  'label': {
    'block': true,
    'text-zinc-700': true,
    'text-base': true,
    'font-bold': true,
    'mb-1.5': true,
    'dark:text-zinc-300': true
  },
  'legend': {
    'block': true,
    'text-zinc-700': true,
    'text-base': true,
    'font-bold': true,
    'dark:text-zinc-300': true
  },
  'input': {
    'appearance-none': true,
    '[color-scheme:light]': true,
    'dark:[color-scheme:dark]': true,
    'selection:bg-zinc-100': true,
    'selection:text-zinc-700': true,
    'group-data-[has-overlay]:selection:!text-transparent': true
  },
  'prefixIcon': {
    'flex': true,
    'items-center': true,
    '-ml-1': true,
    'mr-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true
  },
  'suffixIcon': {
    'flex': true,
    'items-center': true,
    '-mr-1.5': true,
    'ml-2.5': true,
    'text-lg': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true
  },
  'loaderIcon': {
    'animate-spin': true,
    'flex': true,
    'items-center': true,
    'my-auto': true,
    'ml-2.5': true,
    'text-lg': true,
    'text-zinc-500': true,
    'h-[1em]': true,
    'w-[1em]': true,
    'shrink-0': true,
    '[&>svg]:w-full': true
  },
  'loadMoreInner': {
    'flex': true,
    'text-base': true,
    'text-zinc-500': true,
    'p-2.5': true,
    'items-center': true,
    'justify-center': true,
    '[&>span]:mr-2.5': true
  },
  'help': {
    'text-zinc-500': true,
    'text-sm': true,
    'dark:text-zinc-400': true
  },
  'message': {
    'text-red-500': true,
    'mb-2': true,
    'text-sm': true,
    'dark:text-red-400': true
  },
  // 'overlay': {
  //   'text-zinc-700': true,
  //   'dark:text-zinc-300': true
  // },
  // 'overlayPlaceholder': {
  //   'text-zinc-400': true,
  //   'dark:text-zinc-400/50': true
  // },
  // 'overlayLiteral': {
  //   'text-zinc-700': true,
  //   'dark:text-zinc-300': true
  // },
  // 'overlayChar': {
  //   'text-zinc-700': true,
  //   'dark:text-zinc-300': true
  // },
  // 'overlayEnum': {
  //   'text-zinc-700': true,
  //   'dark:text-zinc-300': true
  // }
}
